### ISSUE TITLE
oneClipper for Firefox?

### ISSUE THREAD

**Issue by catspyjamas2** [anilkumarum/one-clipper#1]
Hello, would you please consider developing the oneClipper addon for Mozilla Firefox? MS deleted the official OneNote Webclipper from the Firefox addon store several months ago, to encourage the use of their own Edge browser. They've also disabled it from working in machines where the OneNote Webclipper addon is already installed on Firefox.

You've made such a great a great chromium webclipper for OneNote, it'd be great to have an option back for Firefox! 

Thanks so much for providing this MV3 option for Chrome. It works flawlessly.

I can't see how to add a label, but I guess it would be "enhancement" as it is a development suggestion.

**Comment by anilkumarum** [comment]
Happy to know that you like this extension.
I am working on this issue. I am changing code to run oneClipper on firefox.
 I will launch oneClipper for Firefox within a week.
Very difficult to port Chrome extension to Mozilla. It is time -consuming. Hard to debug

**Comment by catspyjamas2** [comment]
Ah that's great news! Thanks so much - especially as the porting to Mozilla is time-consuming and not straightforward. Really appreciate how proactively you are developing  this addon - I have noticed how quickly you implement suggestions & fix bugs  that are mentioned in the review comments in the Chrome Store. It's refreshing. :)

This addon for OneNote in Firefox will be welcome news to many!

**Comment by anilkumarum** [comment]
OneClipper firefox add-on submitted for review. Publish after review. 
Extension is experimental and has minor bugs.

**Comment by spamspambaconspam** [comment]
Thank you for making this extension!
I have installed it and will start a new issue with my first hurdle.

**Comment by catspyjamas2** [comment]
> OneClipper firefox add-on submitted for review. Publish after review. Extension is experimental and has minor bugs.

Hi, thanks so much! Just found & downloaded it. 

You mention minor bugs - is the blank icon in the toolbar one of them? I included a screensnip to show you what I mean. The clipper is pinned there as you can see when I mouse over it in the below image. I tried it with the Firefox default theme in both light & dark to see if it made a difference, I also tried restarting the browser but still doesn't show. I don't see this behaviour in Chrome, just Firefox (131.0 64-bit)

![Screenshot 2024-10-03 170125](https://github.com/user-attachments/assets/c6f5c5f6-4b3f-407b-a25f-7a15d39b4dc8)

**Comment by anilkumarum** [comment]
I update oneClipper firefox add-on with version 0.0.12

1. Forbidden request or other bugs in oAuth process fixed
2. Icon not show in toolbar bug fixed
3. AI summary bug fixed

Please re-install extension.

I hope I will fixed all known bugs and If you find more bugs,please let me know

Thanks
Have a nice day
