### ISSUE TITLE
Goes thru "Connect" steps, but does not connect?

### ISSUE THREAD

**Issue by spamspambaconspam** [anilkumarum/one-clipper#2]
Firefox: 130.0.1 (64-bit)
Microsoft® OneNote® for Microsoft 365 MSO (Version 2409 Build 16.0.18025.20030) 64-bit 

Installed just now and pinned extension to toolbar, as instructed.
(Icon not visible on dark toolbar)

Click on icon and overlay popup instructs me to connect with OneNote.

I follow steps, using my email/account which my MS Office/OneNote install is registered to.

Goes thru steps, allowing me to "grant" and then opens page that states 

> oneClipper
> Access Granted
> 
> Redirect to oneClipper within 10 seconds

But it's stuck there.
I have restarted FF, but every time I try to use the clipper, it's asking me to Connect (again)
.

**Comment by anilkumarum** [comment]
Deployed extension id is different from development extension id so that oAuth server block client request. I just fixed this issue. Now it is working.
Note: AI summary cannot work in this version.  From next version, AI summary will start working.

**Comment by anilkumarum** [comment]
Above mentioned bugs fixed in version 0.0.12

Please re-install extension.

I hope I will fixed all known bugs and If you find more bugs,please let me know

Thanks
Have a nice day
