### ISSUE TITLE
Clip Article button missing

### ISSUE THREAD

**Issue by calydon** [anilkumarum/one-clipper#7]
![Screenshot 2024-12-06 145821](https://github.com/user-attachments/assets/7aa520cc-0765-47de-8cf9-ebf45223dd4e)

1. Navigate to correct notebook
2. Choose 'clip article'
3. Selected article is highlighted (see screenshot) but there is no button available to 'clip' it to the selected notebook.
4. Example URL is https://www.bbc.com/future/article/20230719-the-blue-flash-louis-slotin-accident-manhattan-project-oppenheimer-atomic-bomb

Firefox v133.0 64 bit

The side panel looks promising and I attempted to 'insert' the content using it's functionality but that seems to have not succeeded.

**Comment by calydon** [comment]
I found a workaround by reducing the zoom value of the browser to 60% The clipping toolbar was hidden under the article menu.
![Screenshot 2024-12-06 152006](https://github.com/user-attachments/assets/fec90fd6-0bb1-45d0-b114-00353f62ae4e)

**Comment by anilkumarum** [comment]
Namaste
Thanks for reporting bug.
Bug fixed.
I will update extension in 2-3 days
